### ISSUE TITLE
Doesn't work with the latest beta version of Dominos

### ISSUE THREAD

**Issue by NoShotz** [dekallo/HideButtonGlow#7]
The addon isn't hiding the button glow when using the latest 10.2.5 beta version of Dominos, likely due to the breaking changes mentioned in the changelog for that version of Dominos.

**Comment by ntowle** [comment]
Thanks, added compatibility in https://github.com/dekallo/HideButtonGlow/commit/d7353319b23f909fc884cc3d381b8cd72a44610a.
